### PR TITLE
fix_label_facets

### PR DESCRIPTION
**Pull request by harisbal**
At the moment labels do not get applied to the titles of facets.
This PR fixes this.

### CODE REVIEW

**Comment by harisbal** [comment]
It's just a very minor modification , I can't understand why the PR is rejected..

**Comment by nicolaskruchten** [comment]
The files in this repo have all been moved into the Plotly.py repository actually, since July. If you’ve found an bug with the latest version, I would recommend opening an issue first to discuss it :)

**Comment by nicolaskruchten** [comment]
I suspect the issue you’re trying to address exists in the latest version as well actually: https://github.com/plotly/plotly.py/blob/49e39b13f7b93652ad1c0ea07726cc79efd69872/packages/python/plotly/plotly/express/_core.py#L1285

If you would like to open a PR in that repo I’ll happily review it there! Ideally with a test case as well if possible please :)

**Comment by harisbal** [comment]
Thanks @nicolaskruchten 
I forgot plotly_express merged with plotly. Cheers

**Comment by nicolaskruchten** [comment]
OK I've reproduced and logged it here: https://github.com/plotly/plotly.py/issues/1944

If you want to submit a PR in the other repo we'd appreciate it, otherwise we'll try to fix it for the next release ;)

**Comment by nicolaskruchten** [comment]
Thanks for bringing this to our attention!

**Comment by harisbal** [comment]
I'll give it a go, it seems quite trivial. Thanks for preparing the example.

**Comment by nicolaskruchten** [comment]
We're prepping for a release so I went ahead: https://github.com/plotly/plotly.py/pull/1966 :)

**Comment by harisbal** [comment]
Sorry I couldn't pull this off earlier.
Nice addition, thanks

**Comment by emmanuelle** [comment]
Thank you @harisbal !

**Pull request closed without merging**
