### PR TITLE
Support implicit dataframe argument.

### PR DESCRIPTION
**Pull request by malmaud**
Closes https://github.com/plotly/plotly_express/issues/85.

### CODE REVIEW

**Comment by malmaud** [comment]
This doesn't have tests or graceful error messages yet, but it seems functional.

**Comment by nicolaskruchten** [comment]
Thanks for this! I'll take a closer look at it in a couple of days with an eye towards supporting #37 by extending it :)

**Comment by nicolaskruchten** [comment]
So I really like this, but I'd like to roll it out with support for #37 and I don't think I have the bandwidth to do so before the Plotly.py v4 release, at which point this repo will disappear and the code will move to the plotly.py repo. OK with you if I close this PR and port the patch into the library after the v4 move in July?

**Comment by malmaud** [comment]
Sure.

**Comment by nicolaskruchten** [comment]
This will be implemented as part of https://github.com/plotly/plotly.py/issues/1767 ... thanks for the input and patience :)

**Pull request closed without merging**
